site_name: 我的工作学习生活笔记

# 配置主题，在mkdocs.yml文件下
theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:            # 文档颜色, https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    scheme: default   # 配色方案
    primary: default  # 主色
    accent: red       # 强调色
  features:
    - navigation.tabs # 顶部导航
    # - navigation.sections # 全部展开(非折叠状态)
    # - navigation.expand # 子目录展开
    - navigation.top  # 返回顶部按钮
    - toc.follow

# 插件
plugins:
  - glightbox
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:  # 支持文档创建时间显示， https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
      locale: zh
      enable_creation_date: true
      type: date

# markdown解析扩展
markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html        # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes
  # pymdownx 扩展，参考：https://facelessuser.github.io/pymdown-extensions/
  - pymdownx.inlinehilite   # 单行高亮, 参考: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines
  - pymdownx.critic         # 支持部分字段格式化，参考：https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.highlight      # 支持代码块高亮显示
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:    # 注释 : 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret          # 下划线, 上标 : https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=caret#caret-mark-tilde 
                            #               https://facelessuser.github.io/pymdown-extensions/extensions/caret/
  - pymdownx.mark          # 标记 :https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=caret#caret-mark-tilde
                            #      https://facelessuser.github.io/pymdown-extensions/extensions/mark/
  - pymdownx.tilde          # 删除线, 下标  参考: https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=caret#caret-mark-tilde
                            #                   https://facelessuser.github.io/pymdown-extensions/extensions/tilde/
  - pymdownx.arithmatex:
      generic: true

# 扩展支持， 支持数学符号
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 页面导航
nav:
  - 首页: index.md
  - 技术: 
    - Python:
      - 安装: technology/python/index.md
      - pip: technology/python/pip.md
      - StringIO: technology/python/stringio.md
      - flask: technology/python/flask.md
      - logging: technology/python/logging.md
      - importlib: technology/python/importlib.md
      - crypto: technology/python/pycrypto.md
      - petl: technology/python/petl.md
      - psutil: technology/python/psutil.md
      - Docx: technology/python/docx.md
      - Excel: technology/python/excel.md
      - reportlab: technology/python/reportlab.md
      - alembic: technology/python/alembic.md
      - sqlalchemy: technology/python/sqlalchemy.md
      - 常用函数合集: technology/python/useful_functions.md
    - Linux:
      - 常用资源: technology/linux/usage_source.md
      - 端口占用查找: technology/linux/port.md
      - linux磁盘挂载: technology/linux/disk-mount.md
      - shell脚本实战: technology/linux/shell-scripts.md
    - 前端知识:
      - 基础: technology/front/base.md
      - 工程化流程: technology/front/project.md
      - 包版本知识: technology/front/version.md
      - package.json知识: technology/front/package.md
      - WebAssembly: technology/front/webassembly.md
    - 服务组件:
      - zookeeper: technology/components/zookeeper.md
      - nginx: technology/components/nginx.md
      - supervisor: technology/components/supervisor.md
      - rabbitmq: technology/components/rabbitmq.md
      - kafka: technology/components/kafka.md
      - 无头浏览器: 
        - openchrome: technology/unheadchrome/openchrome.md
        - 环境搭建: technology/unheadchrome/build_env.md
    - 数据库:
      - ClickHouse: technology/database/clickhouse.md
      - MySQL: 
        - mysql8: technology/database/mysql8_install.md
        - 常用操作: technology/database/mysql.md
      - ElasticSearch:
        - elasticsearch-py: technology/database/elasticsearch_py.md
        - elasticsearch-dsl: technology/database/es_dsl.md
        - elasticsearch-aggs: technology/database/es_aggs.md
    - 安全渗透:
      - hydra: technology/security/thc-hydra.md
      - sqlmap: technology/security/sqlmap.md
    - RFC标准:
      - oauth2学习笔记: technology/rfc/oauth2.md
      - Oauth2-RFC6749翻译: technology/rfc/rfc6749.md
      - Oauth2-RFC6750翻译: technology/rfc/rfc6750.md
    - 知识概念:
      - xaas概念: technology/concept/xaas.md
      - 统一用户管理: technology/concept/users.md
      - ETL数据处理: technology/concept/etl.md
      - 数据传输和对接: technology/concept/data_transfer.md
      - 深入理解计算机系统: technology/concept/understand_computer_system.md
    - 其他:
      - 暂无: technology/other/backup.md
  - 阅读: 
    - 英语: 
      - BlueLevel: read/english/bluelevel.md
      - RedLevel: read/english/redlevel.md
    - 如何阅读一本书: read/book/howtoreadbook.md
    - 如何避免愚蠢的见识: read/howtoavoid.md
    - 灵魂的最高处: read/placeofsoul.md
    - 恶意匹配: read/maliciousmatch.md
    - 沟通的艺术:
      - 沟通入门: read/book/artofcommunication01.md
      - 看入人里:自我: read/book/artofcommunication02.md
      - 看入人里:知觉: read/book/artofcommunication03.md
  - 投资: 
    - "理财网站": invest/webs.md
  - 工具: 
    - 仓库合集: tools/repos.md
  - 文档: 
    - 文档合集: documents/docs.md
  - 电子书: e-book.md
  - 其他:
    - 前端常用地址: other/front_links.md
    - 后端常用地址: other/back_links.md
    - 其他常用地址: other/other_links.md
    - 成为高手秘籍: other/become_leader.md
    - 张一鸣微博: other/zym_weibo.md
  - 关于: about.md